spring:
  application:
    name: java-2-final-project
  session:
    timeout: 5s
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql://localhost:3308/spring_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.extra_physical_table_types: PARTITIONED TABLE
  # 로깅 레벨 설정
  logging:
    level:
      org.hibernate.SQL: DEBUG

  flyway:
    clean-disabled: false
    enabled: true
    # 마이그레이션 파일 위치 지정 (기본값)
    locations: classpath:db/migration
    baseline-on-migrate: true

# 내장 웹 서버 설정
server:
  port: 8080
  servlet:
    session:
      timeout: 5s
springdoc:
  swagger-ui:
    enabled: true
